name: ${script}-${model.name}-${data.name}
defaults:
  - _self_
  - data: cifar10
  - model: resnet
  - optimizer: sgd
  - scheduler: step
  - criterion: ce
  - prune: prune_default

device: cuda:0
script: train
epoch: 175
seed: -1

# plot
plot_module: False
plot_in_out: False

date: ${now:%Y-%m-%d}

hydra:
  run:
    dir: logs/${name}/${now:%Y%m_%d%H_%M%S}
  sweep:
    dir: logs/multirun/${name}/${now:%Y%m_%d%H_%M%S}
    subdir: ${hydra.job.num}
  output_subdir: hydra-config
  job:
    chdir: True
