name: ${data.name}-${model.name}/${prune.method.name}-${prune.score.name}-${prune.pwr}/${prune.amount}
defaults:
  - _self_
  - data: tinyimagenet
  - model: resnet
  - optimizer: sgd
  - scheduler: cyc_tri2
  - criterion: ce
  - prune: prune_default

device: cuda:0
script: train
epoch: 175
seed: -1

# plot
plot_module: False
plot_in_out: False

date: ${now:%Y-%m-%d}

hydra:
  run:
    dir: logs/${name}/${now:%Y%m_%d%H_%M%S}
  sweep:
    dir: logs/multirun/${name}/${now:%Y%m_%d%H_%M%S}
    subdir: ${hydra.job.num}
  output_subdir: hydra-config
  job:
    chdir: True
